export const USER_LOGIN_ATTEMPT = "USER_LOGIN_ATTEMPT";
export const USER_LOGIN_SUCCESS1 = "USER_LOGIN_SUCCESS1";
export const USER_LOGIN_SUCCESS2 = "USER_LOGIN_SUCCESS2";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const CLEAR_LOGIN_STATE = "CLEAR_LOGIN_STATE";
