export type BannerImageType = {
  clientId: string;
  type: number;
  bannerId: number;
  displayPeriod: number;
  contentType: string;
  contentLength: number;
  contents: string;
  alt: string;
  id: string;
};

export type BitpanelType = {
  error: object | undefined;
  status: string | boolean;
  message: string | undefined;
  name: string | undefined;
  googleId: string | undefined;
  language: string | undefined;
  minimumPasswordLength: number;
  maximumPasswordLength: number;
  sessionTimeout: number;
  timeZone: string | undefined;
  tzOffset: number;
  usernamePrompt: string | undefined;
  bitPanel: {
    clientId: string | undefined;
    strikeBlocking: number;
    accountAlertType: number;
    aliases: boolean;
    billPayType: number;
    checkImaging: boolean;
    checkReorderType: number;
    debitCreditColumn: number;
    draftWithdrawal: boolean;
    eMsgCenter: boolean;
    eStatements: number;
    transactionDownload: number;
    fundsTransfers: boolean;
    loanPayments: boolean;
    userRelationType: number;
    lostATMNotification: boolean;
    minimumBalance: boolean;
    multiLingual: boolean;
    nonRelatedAccountTransfers: boolean;
    pendingTransactionType: number;
    pinChangeVariations: boolean;
    runningBalance: number;
    stopPayment: boolean;
    transactionDescription: number;
    vcall: boolean;
    autoposting: number;
    billPayOnly: boolean;
    accountDescription: boolean;
    showAvailableBalance: number;
    accountDisplay: number;
    addFeeColumn: boolean;
    accessPIN: number;
    isBank: boolean;
    timeDateStamp: number;
    demoSite: boolean;
    ibDisclosure: boolean;
    live: boolean;
    liveType: number;
    accessIDFromDB: boolean;
    ibTest: boolean;
    accountDescPropercase: boolean;
    ninetyDaysHistory: boolean;
    audioBillPay: boolean;
    draftWithdrawalInputOptions: number;
    loanShareAccountSplit: boolean;
    principalInterestFlag: boolean;
    displayLastLogin: number;
    profileUpdateAlert: boolean;
    ezApp: number;
    timezoneFlag: boolean;
    partialLoanPayments: boolean;
    international: boolean;
    itpType: number;
    eStatementsOnly: boolean;
    forgotPassword: boolean;
    internetTwoFactorAuthentication: number;
    forceMemberProfile: boolean;
    twoFactorCaseInsensitive: boolean;
    audioTwoFactorAuthentication: number;
    displayEStatement: boolean;
    audioTwoFactorAuthenticationExpiration: number;
    audioUsageInactivityExpiration: number;
    internetTwoFactorAuthenticationExpiration: number;
    internetUsageActivityExpiration: number;
    accessIDPerAccount: number;
    billPayDisclosure: boolean;
    consignmentPurchases: boolean;
    removeVisualEncryption: boolean;
    principalOnlyPayment: boolean;
    loanApplication: number;
    creditcardApplication: boolean;
    membershipApplication: boolean;
    ibAccountSummaryIcon: boolean;
    eStatementDisclosure: boolean;
    blockIBAccounts: boolean;
    oscarHardwareTFA: boolean;
    dpSolution: number;
    oscarMultiUserAccess: boolean;
    fItoFITransfer: boolean;
    mobileBillpay: number;
    minTFAQuestions: number;
    tfaQuestionsToPrompt: number;
    lpmtOptions: boolean;
    disableNewUserTab: boolean;
    optOutKeys: number;
    isOscarImpersonateEnabled: boolean;
    isTaxFormEnabled: boolean;
    deletePendingTransfers: boolean;
    mobileAutoRedirection: boolean;
    ofm: number;
    hasGoogleAnalytics: boolean;
    hasOnDemandTxtMsg: boolean;
    notDisplayZeroInterest: boolean;
    canDisplayHolds: boolean;
    hasESafe: boolean;
    disableTFAAuth: boolean;
    sameDayPendingXfers: boolean;
    userAccessAdmin: boolean;
    audioSSNLogin: number;
    eStmtProvider: number;
    billPayTransferChallengeQuestions: boolean;
    lockoutResponseRetention: number;
    maskAccount: boolean;
    maskSSN: boolean;
    loginImage: boolean;
    passwordMeter: boolean;
    checkReorderSpeedBump: boolean;
    commercialACH: boolean;
    alternateAudioMenu: boolean;
    transfersUserDefinedDescriptions: boolean;
    homeScreenAccordionMenu: boolean;
    mTellerAppPendingTxns: boolean;
    playAvailBalOnvTeller: number;
    eMessageEMailNotification: boolean;
    unmaskAccountsInEMailNotifications: boolean;
    rdc: boolean;
    interestOnlyPayment: boolean;
    depositImages: boolean;
    eStatementOptOutWithNoStatements: boolean;
    vTellerPINRelation: number;
    livePINRequired: boolean;
    loanHistoryForOneYear: number;
    jhaepssso: boolean;
    jhaachrdxsso: boolean;
    usernamePrompt: number;
    mTellerAppExpiration: number;
    minimumPasswordRequirements: number;
    loanApps: number;
    depositHistoryPeriod: number;
    hasShazamIndirectRelationships: boolean;
    hasFingerprintLoginAndroid: boolean;
    hasFingerprintLoginiOS: boolean;
    mTellerLoanApp: boolean;
    allowVTellerPINSLastFourSSN: boolean;
    mTellerMarketingBanners: boolean;
    mTellerCustomizableFooters: boolean;
    disableVTellerTransferPIN: boolean;
    rdcProvider: number;
    anonymousEZAppSubmission: boolean;
    ezAppAttachments: boolean;
    iPayP2PMobileApp: boolean;
    usernameRequirements: number;
    id: string | undefined;
  };
  uiSettings: {
    clientId: string | undefined;
    font: string | undefined;
    color1: string | undefined;
    color2: string | undefined;
    color3: string | undefined;
    messageBoard: string | undefined;
    loanAppUrl: string | undefined;
    linkColor: string | undefined;
    id: string | undefined;
  };

  bannerImages: {
    loginBanner: BannerImageType | undefined;
    headerBanner: BannerImageType | undefined;
  };
};
