export const CHECK_IMAGE_ATTEMPT = "CHECK-IMAGE_ATTEMPT";
export const CHECK_IMAGE1_SUCCESS = "CHECK-IMAGE1_SUCCESS";
export const CHECK_IMAGE2_SUCCESS = "CHECK-IMAGE2_SUCCESS";
export const CHECK_IMAGE_FAIL = "CHECK-IMAGE_FAIL";
export const CHECK_IMAGE1_CLEAR = "CHECK_IMAGE1_CLEAR";
export const CHECK_IMAGE2_CLEAR = "CHECK_IMAGE2_CLEAR";
