export const CLIENT_SETTINGS_ATTEMPT = "CLIENT_SETTINGS_ATTEMPT";
export const CLIENT_SETTINGS_SUCCESS = "CLIENT_SETTINGS_SUCCESS";
export const CLIENT_SETTINGS_FAIL = "CLIENT_SETTINGS_FAIL ";
export const CLEAR_CLIENT_STATE = "CLEAR_CLIENT_STATE";
